# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TheBitterSweet.Me
email: ronald.peic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What is the purpose of this site? I have long considered logging some of my more intense musings 
  for the purpose of recording significant events and adjusting to my poor memory. However, a more
  potent idea had been realised: I should log events as often as necessary, only so as to paint my
  decomposing humanity and the inevitability that is to be my untimely end. 
  Also, not to forget the impetus of finally buying a domain name (12/11/16): Tablo's BloNotes 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://thebittersweet.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jiggaPls

# Build settings
markdown: kramdown
